var __extends=this&&this.__extends||function(c,h){function n(){this.constructor=c}for(var m in h)h.hasOwnProperty(m)&&(c[m]=h[m]);c.prototype=null===h?Object.create(h):(n.prototype=h.prototype,new n)},js;
(function(c){var h=function(){function b(){this._slaves=[]}b.prototype.manage=function(a){this._slaves.push(a);a.init()};b.prototype.dispose=function(){for(var a=0;a<this._slaves.length;a++)this._slaves[a].dispose()};b.prototype.getViewModel=function(){return null};b.prototype.getParent=function(){return null};b.prototype.onUnrender=function(){return new x};return b}();c.ExplicitManager=h;c.observableValue=function(){return new p};c.observableList=function(){return new y};c.dependentValue=function(b){for(var a=
[],d=1;d<arguments.length;d++)a[d-1]=arguments[d];return new B(b,a)};c.init=function(){var b=new C,a=(new D).registerFetcher(q.Value,new E).registerFetcher(q.CheckedAttribute,new F),d=new G(b),b=new H(function(a){return a.toString()},b,d,a),a=new I(b,d,a);d.setDomFactory(a);c.dom=a.create(new J($(document)),new h)};var n=function(){function b(a,d,b,f,c){this._manager=a;this._event=d;this._target=b;this._options=f;this._fetcherFactory=c}b.prototype.react=function(a,d){var b=null,b=this._options&&this._options.fetch?
this._fetcherFactory.getByKey(this._options.fetch):this._fetcherFactory.getForElement(this._target),f=null;b&&(f=function(a){return b.valueFromElement(a)});var c=d||this._manager.getViewModel(),f=new m(f,this._event,a,this._target,c);this._manager.manage(f)};return b}();c.CommandConfig=n;var m=function(){function b(a,d,b,f,c){this._argumentFetcher=a;this._eventType=d;this._callback=b;this._target=f;this._context=c}b.prototype.dispose=function(){this._target.detachEventHandler(this._eventType,this._handlerRef)};
b.prototype.init=function(){var a=this;this._handlerRef=this._target.attachEventHandler(this._eventType,function(){var d=null==a._argumentFetcher?null:a._argumentFetcher(a._target);null==d?a._callback.call(a._context):a._callback.call(a._context,d)})};return b}();c.CommandWire=m;var k;(function(b){b.text="text";b.html="html";b.unknown="unknown"})(k=c.ValueType||(c.ValueType={}));var W=function(){function b(a,d,b,f,c){this._rootElement=a;this._manager=d;this._renderListenerFactory=b;this._viewFactory=
f;this._fetcherFactory=c;this.root=a;this.$=a.$;this.manager=d}b.prototype.find=function(a){a=new V(this._rootElement.findRelative(a),this._manager,this._renderListenerFactory,this._viewFactory,this._fetcherFactory);return l.wrapObjectWithSelfFunction(a,function(a,b,f){a.observes(b,f)})};b.prototype.dispose=function(){this._manager.dispose()};b.prototype.onUnrender=function(){return this._manager.onUnrender()};return b}(),V=function(){function b(a,d,b,f,c){var e=this;this._rootElement=a;this._manager=
d;this._renderListenerFactory=b;this._viewFactory=f;this._fetcherFactory=c;this.root=a;a=new t(this._manager,function(a){return e.createRenderListener(a,{valueType:k.text})});d=new t(this._manager,function(a){return e.createRenderListener(a,{valueType:k.html})});this.$=this._rootElement.$;this.text=l.wrapObjectWithSelfFunction(a,function(a,d){return a.observes(d)});this.html=l.wrapObjectWithSelfFunction(d,function(a,d){return a.observes(d)});this.manager=this._manager}b.prototype.listener=function(a){var d=
this;return new t(this._manager,function(b){return d.createRenderListener(b,{renderer:new K(a)})})};b.prototype.className=function(a){return this.listener(function(d,b){b?d.addClass(a):d.removeClass(a)})};b.prototype.observes=function(a,d){var b=u.getObservable(a);d&&l.isFunction(d)&&(d={view:d});b=this.createRenderListener(b,d);this._manager.manage(b)};b.prototype.render=function(a,d){var b=this._viewFactory.resolve(this._rootElement,a,d,this._manager);this._manager.manage(b)};b.prototype.on=function(a,
d){return new n(this._manager,a,this._rootElement,d,this._fetcherFactory)};b.prototype.createRenderListener=function(a,d){return this._renderListenerFactory.createListener(a,this,d)};return b}(),t=function(){function b(a,d){this._manager=a;this.factory=d}b.prototype.observes=function(a){a=u.getObservable(a);a=this.factory(a);this._manager.manage(a)};return b}();c.ObservationConfig=t;var u;(function(b){b.getObservable=function(a){return a&&a.getValue&&a.listen?a:new L(a)}})(u||(u={}));var I=function(){function b(a,
d,b){this._renderListenerFactory=a;this._viewFactory=d;this._fetcherFactory=b}b.prototype.create=function(a,d){var b=new W(a,d,this._renderListenerFactory,this._viewFactory,this._fetcherFactory);return l.wrapObjectWithSelfFunction(b,function(a,b){return a.find(b)})};return b}();c.DomFactory=I;var x=function(){function b(){this._listeners=[]}b.prototype.listen=function(a){var b=this;this._listeners.push(a);return{dispose:function(){b.removeListener(a)}}};b.prototype.trigger=function(a){for(var b=0;b<
this._listeners.length;b++)this._listeners[b](a)};b.prototype.dispose=function(){this._listeners=null};b.prototype.getListenersCount=function(){return null===this._listeners?0:this._listeners.length};b.prototype.hasListeners=function(){return 0<this.getListenersCount()};b.prototype.removeListener=function(a){v.removeItem(this._listeners,a)};return b}();c.Event=x;var q=function(){return function(){}}();q.Value="value";q.CheckedAttribute="checkedAttribute";c.FetcherType=q;var E=function(){function b(){}
b.prototype.isSuitableFor=function(a){var b=a.getNodeName();return b&&(b=b.toUpperCase(),"TEXTAREA"===b||"SELECT"===b||"INPUT"===b&&(a=a.getAttribute("type"),!a||"TEXT"===a.toUpperCase()))?!0:!1};b.prototype.valueToElement=function(a,b){b.setValue(a)};b.prototype.valueFromElement=function(a){return a.getValue()};return b}();c.ValueFetcher=E;var F=function(){function b(){}b.prototype.isSuitableFor=function(a){var b=a.getNodeName();return b?(b=b.toUpperCase(),a=a.getAttribute("type"),"INPUT"===b&&a&&
"CHECKBOX"===a.toUpperCase()):!1};b.prototype.valueToElement=function(a,b){b.setProperty("checked",a)};b.prototype.valueFromElement=function(a){var b=!1;a.getProperty("checked")&&(b=!0);return b};return b}();c.CheckedAttributeFetcher=F;var D=function(){function b(){this._items={}}b.prototype.getForElement=function(a){for(var b in this._items){var e=this._items[b];if(e.isSuitableFor(a))return e}return null};b.prototype.getByKey=function(a){return this._items[a]};b.prototype.registerFetcher=function(a,
b){this._items[a]=b;return this};return b}();c.FetcherFactory=D;var J=function(){function b(a){this._target=this.$=a}b.prototype.empty=function(){this._target.empty()};b.prototype.appendHtml=function(a){if(null===a||void 0===a)throw Error("Could not append empty string!");if("string"!==typeof a)throw Error("Expected string markup but was"+a);a=$($.parseHTML(a));this._target.append(a);return new b(a)};b.prototype.getNodeName=function(){return 1==this._target.length?this._target[0].nodeName:null};b.prototype.findRelative=
function(a){var d=this._target.filter(a);0==d.length&&(d=this._target.find(a));return new b(d)};b.prototype.remove=function(){this._target.remove()};b.prototype.getTarget=function(){return this._target};b.prototype.setText=function(a){this._target.text(a)};b.prototype.setHtml=function(a){this._target.html(a)};b.prototype.addClass=function(a){this._target.addClass(a)};b.prototype.removeClass=function(a){this._target.removeClass(a)};b.prototype.attachEventHandler=function(a,d){var e=function(){d(new b($(this)));
return!1};this._target.on(a,e);return e};b.prototype.detachEventHandler=function(a,b){this._target.off(a,b)};b.prototype.getValue=function(){return this._target.val()};b.prototype.setValue=function(a){return this._target.val(a)};b.prototype.getAttribute=function(a){return this._target.attr(a)};b.prototype.setAttribute=function(a,b){this._target.attr(a,b)};b.prototype.getProperty=function(a){return this._target.prop(a)};b.prototype.setProperty=function(a,b){this._target.prop(a,b)};return b}();c.JQueryElement=
J;var C=function(){function b(){}b.prototype.resolve=function(a){var b;if(a instanceof jQuery)b=a;else try{b=$(a)}catch(e){return a}if(0<b.parent().length)return b.html();if("string"===typeof a)return a;if(a instanceof jQuery)return $("<p>").append(a).html();throw Error("Could not resolve markup by object "+a);};return b}();c.JQueryMarkupResolver=C;var K=function(){function b(a){this.payload=a}b.prototype.render=function(a,b){this.payload(b,a);return{element:b,dispose:function(){}}};return b}();c.CustomListenerRenderer=
K;var M=function(){function b(a,b,e){this._observable=a;this._contentDestination=b;this._renderer=e}b.prototype.init=function(){var a=this;this._link=this._observable.listen(function(b){return a.doRender(b)})};b.prototype.dispose=function(){this._link&&this._link.dispose();this.disposeCurrentValue()};b.prototype.doRender=function(a){this.disposeCurrentValue();this._currentValue=this._renderer.render(a,this._contentDestination)};b.prototype.disposeCurrentValue=function(){this._currentValue&&this._currentValue.dispose()};
return b}();c.RenderValueListener=M;var N=function(){function b(a,b,e){this._observable=a;this._contentDestination=b;this._renderer=e;this._renderedValues=[]}b.prototype.dispose=function(){this._link&&this._link.dispose();for(var a=0;a<this._renderedValues.length;a++)this._renderedValues[a].renderedValue.dispose&&this._renderedValues[a].renderedValue.dispose()};b.prototype.init=function(){var a=this;this._link=this._observable.listen(function(b,e,f){return a.doRender(f.portion,f.reason)})};b.prototype.findRenderedValue=
function(a){for(var b=0;b<this._renderedValues.length;b++)if(this._renderedValues[b].value===a)return this._renderedValues[b].renderedValue;return null};b.prototype.removeRenderedValue=function(a){for(var b=-1,e=0;e<this._renderedValues.length;e++)this._renderedValues[e].renderedValue===a&&(b=e);0<=b&&this._renderedValues.splice(b,1)};b.prototype.doRender=function(a,b){if(b==g.remove)for(var d=0;d<a.length;d++){var f=this.findRenderedValue(a[d]);f&&(f.dispose(),this.removeRenderedValue(f))}else b!=
g.add&&(this._renderedValues=[],this._contentDestination.empty()),this.appendItems(a)};b.prototype.appendItems=function(a){if(a)for(var b=0;b<a.length;b++){var e=a[b],f=this._renderer.render(e,this._contentDestination);this._renderedValues.push({value:e,renderedValue:f})}};return b}();c.RenderListHandler=N;var H=function(){function b(a,b,e,f){this._defaultFormatter=a;this._markupResolver=b;this._viewFactory=e;this._fetcherFactory=f}b.prototype.createListener=function(a,b,e){var d=b.root;e||(e={});
if(!e.renderer)if(e.view)e.renderer=new O(this._viewFactory,e.view,b.manager);else{if(!e.valueType)if(e.formatter)e.valueType=k.unknown;else{var c=!0;void 0!==e.encode&&(c=e.encode);e.valueType=c?k.text:k.html}e.formatter||(e.formatter=this._defaultFormatter);e.renderer=this.getRenderer(e,b,a)}return this.isList(a)?new N(a,d,e.renderer):new M(a,d,e.renderer)};b.prototype.getRenderer=function(a,b,e){var d;if(a.fetch){if(d=this._fetcherFactory.getByKey(a.fetch),!d)throw Error("Fetcher "+a.fetch+" not found");
}else if(d=this._fetcherFactory.getForElement(b.root),!1!==a.bidirectional){var c=a.command,r=a.commandContext,g=a.event||"change";!c&&e.setValue&&(c=e.setValue,r=e);c&&b.on(g).react(c,r)}if(d)return new P(d);switch(a.valueType){case k.text:return new Q(a.formatter);case k.html:return new R(a.formatter);case k.unknown:return new S(a.formatter,this._markupResolver);default:throw Error("Unknown value type: "+a.valueType);}};b.prototype.isList=function(a){return a instanceof y||a&&a.getValue()instanceof
Array?!0:!1};return b}();c.RenderListenerFactory=H;var g;(function(b){b[b.replace=0]="replace";b[b.add=1]="add";b[b.remove=2]="remove";b[b.initial=3]="initial"})(g=c.DataChangeReason||(c.DataChangeReason={}));var T=function(){function b(a,b){this.allListeners=a;this.currentListener=b}b.prototype.dispose=function(){v.removeItem(this.allListeners,this.currentListener)};return b}();c.ListenerLink=T;var p=function(){function b(){this._listeners=[]}b.prototype.getValue=function(){return this._value};b.prototype.setValue=
function(a){var b=this._value;this._value=a;this.notifyListeners(a,b,{reason:g.replace,portion:a})};b.prototype.listen=function(a,b){this._listeners.push(a);void 0!==b&&!0!==b||this.notifyListeners(this.getValue(),this.getValue(),{reason:g.initial,portion:this.getValue()});return new T(this._listeners,a)};b.prototype.getListenersCount=function(){return this._listeners.length};b.prototype.getListener=function(a){return this._listeners[a]};b.prototype.notifyListeners=function(a,b,e){for(var d=0;d<this._listeners.length;d++)this._listeners[d](a,
b,e)};b.prototype.hasValue=function(){return null==this._value||void 0==this._value?!1:!0};return b}();c.ObservableValue=p;var y=function(b){function a(){var a=b.call(this)||this;b.prototype.setValue.call(a,[]);return a}__extends(a,b);a.prototype.setValue=function(a){if(a&&!(a instanceof Array))throw Error("Observable list supports only array values");b.prototype.setValue.call(this,a);this.notifyCountListeners()};a.prototype.add=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];
for(var b=this.getValue().slice(0),f=this.getValue(),c=0;c<a.length;c++)f.push(a[c]);this.reactOnChange(this.getValue(),b,{reason:g.add,portion:a})};a.prototype.remove=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];for(var b=this.getValue().slice(0),c=this.getValue(),z=0;z<a.length;z++)v.removeItem(c,a[z]);this.reactOnChange(this.getValue(),b,{reason:g.remove,portion:a})};a.prototype.clear=function(){var a=this.getValue().splice(0,this.getValue().length);this.reactOnChange(this.getValue(),
a,{reason:g.remove,portion:a})};a.prototype.count=function(){this._count||(this._count=new p,this.notifyCountListeners());return this._count};a.prototype.forEach=function(a,b){this.getValue().forEach(a,b)};a.prototype.reactOnChange=function(a,e,c){b.prototype.notifyListeners.call(this,a,e,c);this.notifyCountListeners()};a.prototype.notifyCountListeners=function(){this._count&&(this.getValue()?this._count.setValue(this.getValue().length):this._count.setValue(0))};return a}(p);c.ObservableList=y;var B=
function(b){function a(a,e){var d=b.call(this)||this;d._dependencies=e;d._evaluateValue=a;d._dependencyValues=[];for(var c=0;c<e.length;c++){var r=e[c];d.setupListener(r);d._dependencyValues[c]=r.getValue()}return d}__extends(a,b);a.prototype.getValue=function(){return this._evaluateValue.apply(this,this._dependencyValues)};a.prototype.setValue=function(a){throw Error("Could not set dependent value");};a.prototype.notifyDependentListeners=function(a,b){for(var d=this.getValue(),e=0;e<this._dependencies.length;e++)this._dependencies[e]===
a&&(this._dependencyValues[e]=b);for(var c=this.getValue(),e=0;e<this.getListenersCount();e++)this.getListener(e)(c,d,{portion:c,reason:g.replace})};a.prototype.setupListener=function(a){var b=this;a.listen(function(d,e,c){c.reason!==g.replace&&(d=a.getValue());b.notifyDependentListeners(a,d)},!1)};return a}(p);c.DependentValue=B;var L=function(){function b(a){this._value=a}b.prototype.getValue=function(){return this._value};b.prototype.listen=function(a){a(this.getValue(),null,{reason:g.initial,
portion:this.getValue()});return{dispose:function(){}}};return b}();c.StaticObservableValue=L;var w=function(){function b(a){this._formatter=a}b.prototype.render=function(a,b){var d=this,c=this._formatter(l.isNullOrUndefined(a)?"":a);this.doRender(c,b);return{dispose:function(){d.doRender("",b)}}};b.prototype.doRender=function(a,b){};return b}();c.FormatterBasedRenderer=w;var Q=function(b){function a(a){return b.call(this,a)||this}__extends(a,b);a.prototype.doRender=function(a,b){b.setText(a)};return a}(w);
c.TextRenderer=Q;var R=function(b){function a(a){return b.call(this,a)||this}__extends(a,b);a.prototype.doRender=function(a,b){b.setHtml(a)};return a}(w);c.HtmlRenderer=R;var S=function(b){function a(a,e){var d=b.call(this,a)||this;d._markupResolver=e;return d}__extends(a,b);a.prototype.doRender=function(a,b){var d=this._markupResolver.resolve(a);b.setHtml(d)};return a}(w);c.ResolvableMarkupRenderer=S;var O=function(){function b(a,b,e){this._parent=e;this._viewFactory=a;this._viewDescriptor=b}b.prototype.render=
function(a,b){if(l.isNullOrUndefined(a))return A.noopDisposable;var d=this._viewFactory.resolve(b,this._viewDescriptor,a,this._parent);d.init();return{dispose:function(){d.dispose()}}};return b}();c.ViewValueRenderer=O;var P=function(){function b(a){this._fetcher=a}b.prototype.render=function(a,b){this._fetcher.valueToElement(a,b);return A.noopDisposable};return b}();c.FetcherToRendererAdapter=P;var l;(function(b){b.isNullOrUndefined=function(a){return null===a||void 0===a};b.isFunction=function(a){var b=
{};return a&&"[object Function]"===b.toString.call(a)};b.wrapObjectWithSelfFunction=function(a,b){var d=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];a.splice(0,0,d);return b.apply(this,a)},c;for(c in a)d[c]=a[c];return d}})(l=c.Utils||(c.Utils={}));var v;(function(b){b.removeItem=function(a,b){for(var d=-1,c=0;c<a.length;c++)a[c]===b&&(d=c);0<=d&&a.splice(d,1)}})(v=c.ArrayUtils||(c.ArrayUtils={}));var A;(function(b){b.noop=function(){};b.noopDisposable={dispose:b.noop}})(A=
c.DisposingUtils||(c.DisposingUtils={}));var U=function(){function b(a,b,c,f,g,h){this._viewData=a;this._viewModel=b;this._markupResolver=c;this._destination=f;this._domFactory=g;this._parent=h;this._slaves=[];this._unrender=new x}b.prototype.onUnrender=function(){return this._unrender};b.prototype.manage=function(a){this._slaves.push(a)};b.prototype.init=function(){var a=this._markupResolver.resolve(this._viewData.template),a=this._destination.appendHtml(a);this.attachViewToRoot(a)};b.prototype.getViewModel=
function(){return this._viewModel};b.prototype.getParent=function(){return this._parent};b.prototype.attachViewToRoot=function(a){this._root=a;if(this._viewData.init)if(a=this._domFactory.create(this._root,this),0<this._viewData.deep){var b=this.fetchViewModels(this._viewData.deep);b.splice(0,0,this._viewModel);b.splice(0,0,a);this._viewData.init.apply(this._viewData,b)}else this._viewData.init(a,this._viewModel);for(a=0;a<this._slaves.length;a++)this._slaves[a].init();this._viewModel&&this._viewModel.initState&&
this._viewModel.initState()};b.prototype.getRootElement=function(){return this._root};b.prototype.unrenderView=function(){this._unrender.hasListeners()?this._unrender.trigger():this.getRootElement().remove()};b.prototype.dispose=function(){this.unrenderView();this._viewModel&&this._viewModel.releaseState&&this._viewModel.releaseState();for(var a=0;a<this._slaves.length;a++)this._slaves[a].dispose()};b.prototype.fetchViewModels=function(a){for(var b=[],c=this.getParent(),f=1;f<=a&&null!==c;)b.push(c.getViewModel()),
c=c.getParent(),f++;return b};return b}();c.ComposedView=U;var G=function(){function b(a){this._markupResolver=a}b.prototype.setDomFactory=function(a){this._domFactory=a};b.prototype.resolve=function(a,b,c,f){if(!b)throw Error("Expected view data object was not defined");if(l.isFunction(b))return b=new b,this.resolve(a,b,c,f);if(b.template)return new U(b,c,this._markupResolver,a,this._domFactory,f);if(b.renderTo&&b.getRootElement)return b;throw Error("Could not resolve view data by provided descriptor");
};return b}();c.DefaultViewFactory=G})(js||(js={}));js.init();
