//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyProductAttribute("CrystalQuartz")]
[assembly: AssemblyVersionAttribute("7.0.0.20")]
[assembly: AssemblyFileVersionAttribute("7.0.0.20")]
